name: Deploy Cloud Functions
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - name: Deploy to Cloud Functions
        if: startsWith(github.refname, 'renovate') == false
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "roe2-prod"
        with:
          args: deploy -f --only functions,storage,database,firestore
